<b> 
Policy iteration에서는 상태가치함수를 반복적으로 갱신해야한다. 다음 그림 S에서 시작하여 T에 도착하려 한다. <br>
    
* Agent는 Random Pocliy를 따름
* <span style="color:red">함정</span>에 도달하는 경우 -0.1, 목적지(T)에 도착하는 경우 1을 보상으로 부여
* $\gamma = 1$
</b>

<img src="grid.png" width="200" height="200"/>

<b>
[문제 1]
    
$k=2$일 때, 상태가치함수를 구하시오.

<img src="문제1.png" width="300" height="400"/>

In [1]:
import numpy as np

# 환경 설정
num_rows = 3
num_cols = 3
num_actions = 4 
trap_locations = [(1,3), (3, 1)]
goal_location = (3,3)
discount_factor = 1.0

# 정책 설정 
policy = np.full((num_rows + 2,num_cols + 2,num_actions),0.25)

# 초기화
value_function=np.zeros((num_rows +2 , num_cols +2))

for k in range(2):   # 반복수
    new_value_function=np.zeros((num_rows +2 , num_cols +2))
    for i in range(1,num_rows+1): # 행
        print()
        for j in range(1,num_cols+1): # 열
            print("==================================================================")
            for action in range(num_actions):
                if action==0: next_i,next_j=max(i-1,1),j     #상 
                elif action==2: next_i,next_j=i,max(j-1,0)   # 좌
                elif action==3: next_i,next_j=i,min(j+1,num_cols) # 우
                else : next_i,next_j=min(i+1,num_rows),j     # 하
                
                trap = ((i,j)==(1, 3)) and (action == 0 or action == 3) or ((i,j)==(3, 1)) and (action == 1 or action == 2) 
                
                reward= -0.1 if ((next_i,next_j) in trap_locations or trap) else \
                        (+1 if (next_i,next_j)==goal_location else .0)
                
               
                new_value_function[i][j] += policy[i][j][action]*(reward+(discount_factor*value_function[next_i][next_j])) # 상태가치
                
                print(f"k={k+1}, ({i}, {j}), Action={action}: 식", policy[i][j][action], "*", "(", reward, "+", discount_factor, "*", value_function[next_i][next_j], ")")
    
    value_function=new_value_function.copy()
    
    print(f"\nk={k+1}")
    print("상태가치:")
    print(new_value_function[1:num_rows+1, 1:num_cols+1])



k=1, (1, 1), Action=0: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 1), Action=1: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 1), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 1), Action=3: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 2), Action=0: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 2), Action=1: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 2), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 2), Action=3: 식 0.25 * ( -0.1 + 1.0 * 0.0 )
k=1, (1, 3), Action=0: 식 0.25 * ( -0.1 + 1.0 * 0.0 )
k=1, (1, 3), Action=1: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 3), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 3), Action=3: 식 0.25 * ( -0.1 + 1.0 * 0.0 )

k=1, (2, 1), Action=0: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 1), Action=1: 식 0.25 * ( -0.1 + 1.0 * 0.0 )
k=1, (2, 1), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 1), Action=3: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 2), Action=0: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 2), Action=1: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 2), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (

In [4]:
(0.25 * ( 0.0 + 1.0 * 0.0 ))+(0.25 * ( -0.1 + 1.0 * -0.05 ))+(0.25 * ( 0.0 + 1.0 * 0.0 ))+(0.25 * ( 0.0 + 1.0 * 0.0 )) # 2,1

-0.037500000000000006

In [5]:
(0.25 * ( 0.0 + 1.0 * 0.0 ))+(0.25 * ( -0.1 + 1.0 * -0.05 ))+(0.25 * ( 0.0 + 1.0 * 0.0 ))+(0.25 * ( 0.0 + 1.0 * 0.0 )) # 2,1

0.1

In [6]:
(0.25 * ( -0.1 + 1.0 * -0.05 ))+0.25 * ( 1 + 1.0 * 0.5 )+(0.25 * ( 0.0 + 1.0 * 0.0 ))+(0.25 * ( 0.0 + 1.0 * 0.225 )) # 2,3

0.39375000000000004

<b>
[문제 2]

$k=1$ 부터 반복 계산하여 상태가치가 수렴할 때까지의 값을 프로그래밍하시오.

In [9]:
import numpy as np

# 환경 설정
num_rows = 3
num_cols = 3
num_actions = 4 
trap_locations = [(1,3), (3, 1)]
goal_location = (3,3)
discount_factor = 1.0

# 정책 설정 
policy = np.full((num_rows + 2,num_cols + 2,num_actions),0.25)

# 초기화
value_function=np.zeros((num_rows +2 , num_cols +2))

theta=1e-10   #수렴 기준(임계값)
delta=float('inf')   #가치 함수의 변화량 초기화

k=0   #반복 횟수 초기화

while delta>theta:   #while 문
    new_value_function=np.zeros((num_rows +2 , num_cols +2))
    delta=0.0
    
    for i in range(1,num_rows+1): 
        for j in range(1,num_cols+1):
            for action in range(num_actions):
                if action==0: next_i,next_j=max(i-1,1),j     #상 
                elif action==2: next_i,next_j=i,max(j-1,0)   # 좌 
                elif action==3: next_i,next_j=i,min(j+1,num_cols) # 우 
                else : next_i,next_j=min(i+1,num_rows),j     # 하
                
                trap=((i,j)==(1, 3)) and (action == 0 or action == 3) or ((i,j)==(3, 1)) and (action == 1 or action == 2)  
                
                reward=-0.1 if ((next_i,next_j) in trap_locations or trap) else \
                       (+1 if (next_i,next_j)==goal_location else .00)

                new_value_function[i][j] += policy[i][j][action]*(reward+(discount_factor*value_function[next_i][next_j])) 

            delta=max(delta,np.abs(new_value_function[i][j]-value_function[i][j]))   #업데이트
            
    value_function=new_value_function.copy()
    
    print(f"\nk={k+1}")
    print("상태가치:")
    print(new_value_function[1:num_rows+1, 1:num_cols+1])
    
    k+=1   #반복 횟수 카운터 증가
    
    

#     k=417
#     상태가치:
#     [[0.94945055 1.79340659 2.35604395]
#      [1.05494505 2.17472527 3.11868132]
#      [1.19560439 2.73186813 3.92527472]]


k=1
상태가치:
[[ 0.    -0.025 -0.05 ]
 [-0.025  0.     0.225]
 [-0.05   0.225  0.5  ]]

k=2
상태가치:
[[-0.0125  -0.04375 -0.025  ]
 [-0.0375   0.1      0.39375]
 [-0.0125   0.39375  0.8625 ]]

k=3
상태가치:
[[-0.0234375 -0.0203125  0.025    ]
 [-0.00625    0.1765625  0.5578125]
 [ 0.0359375  0.5609375  1.128125 ]]

k=4
상태가치:
[[-0.0125      0.01445313  0.096875  ]
 [ 0.02226563  0.27304688  0.696875  ]
 [ 0.09765625  0.70039062  1.34375   ]]

k=5
상태가치:
[[0.00605469 0.06796875 0.17626953]
 [0.06455078 0.35849609 0.82763672]
 [0.15507812 0.82871094 1.52119141]]

k=6
상태가치:
[[0.03464355 0.12719727 0.26203613]
 [0.10490723 0.4472168  0.94589844]
 [0.21208496 0.94086914 1.67468262]]

k=7
상태가치:
[[0.06668701 0.19277344 0.34929199]
 [0.14848633 0.52971802 1.0574585 ]
 [0.26446533 1.04371338 1.8090332 ]]

k=8
상태가치:
[[0.10198669 0.25961761 0.43720398]
 [0.19021759 0.61060791 1.16137543]
 [0.31416626 1.13673248 1.92980957]]

k=9
상태가치:
[[0.13795547 0.32735405 0.52385025]
 [0.23169022 0.68698578 1.25974922]
 [

<b>
[문제 3]
$k=8$일 때, 정책을 갱신하세요.

In [37]:
import numpy as np

# 환경 설정
num_rows = 3
num_cols = 3
num_actions = 4 
trap_locations = [(1,3), (3, 1)]
goal_location = (3,3)
discount_factor = 1.0

# 정책 설정 
policy = np.full((num_rows + 2,num_cols + 2,num_actions),0.25)

# 초기화
value_function=np.zeros((num_rows +2 , num_cols +2))

for k in range(8):   # 반복수
    new_value_function=np.zeros((num_rows +2 , num_cols +2))
    for i in range(1,num_rows+1): # 행
        print()
        for j in range(1,num_cols+1): # 열
            print("==================================================================")
            for action in range(num_actions):
                if action==0: next_i,next_j=max(i-1,1),j     #상 
                elif action==2: next_i,next_j=i,max(j-1,0)   # 좌
                elif action==3: next_i,next_j=i,min(j+1,num_cols) # 우
                else : next_i,next_j=min(i+1,num_rows),j     # 하
                
                trap = ((i,j)==(1, 3)) and (action == 0 or action == 3) or ((i,j)==(3, 1)) and (action == 1 or action == 2) 
                
                reward= -0.1 if ((next_i,next_j) in trap_locations or trap) else \
                        (+1 if (next_i,next_j)==goal_location else .0)
                
               
                new_value_function[i][j] += policy[i][j][action]*(reward+(discount_factor*value_function[next_i][next_j])) # 상태가치
                
                print(f"k={k+1}, ({i}, {j}), Action={action}: 식", policy[i][j][action], "*", "(", reward, "+", discount_factor, "*", value_function[next_i][next_j], ")")
    
    value_function=new_value_function.copy()
    
    print(f"\nk={k+1}")
    print("상태가치:")
    print(new_value_function[1:num_rows+1, 1:num_cols+1])



k=1, (1, 1), Action=0: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 1), Action=1: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 1), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 1), Action=3: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 2), Action=0: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 2), Action=1: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 2), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 2), Action=3: 식 0.25 * ( -0.1 + 1.0 * 0.0 )
k=1, (1, 3), Action=0: 식 0.25 * ( -0.1 + 1.0 * 0.0 )
k=1, (1, 3), Action=1: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 3), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (1, 3), Action=3: 식 0.25 * ( -0.1 + 1.0 * 0.0 )

k=1, (2, 1), Action=0: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 1), Action=1: 식 0.25 * ( -0.1 + 1.0 * 0.0 )
k=1, (2, 1), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 1), Action=3: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 2), Action=0: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 2), Action=1: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (2, 2), Action=2: 식 0.25 * ( 0.0 + 1.0 * 0.0 )
k=1, (

In [38]:
new_value_function

# k=8
# 상태가치:
# [[0.10198669 0.25961761 0.43720398]
#  [0.19021759 0.61060791 1.16137543]
#  [0.31416626 1.13673248 1.92980957]]

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.10198669, 0.25961761, 0.43720398, 0.        ],
       [0.        , 0.19021759, 0.61060791, 1.16137543, 0.        ],
       [0.        , 0.31416626, 1.13673248, 1.92980957, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [57]:
def max_policy(value_function):
    new_policy=np.zeros((num_rows+2,num_cols+2,num_actions))
    for i in range(1,num_rows+1): # 행
        
        for j in range(1,num_cols+1): # 열
            
            values=[]
            for action in range(num_actions):
                if action==0: next_i,next_j=max(i-1,1),j     #상 
                elif action==2: next_i,next_j=i,max(j-1,0)   # 좌
                elif action==3: next_i,next_j=i,min(j+1,num_cols) # 우
                else : next_i,next_j=min(i+1,num_rows),j     # 하
                
                trap = ((i,j)==(1, 3)) and (action == 0 or action == 3) or ((i,j)==(3, 1)) and (action == 1 or action == 2) 
                
                reward= -0.1 if ((next_i,next_j) in trap_locations or trap) else \
                        (+1 if (next_i,next_j)==goal_location else .0)
                
                values.append(reward+(discount_factor*value_function[next_i][next_j]))
            
            max_value = np.max(values)
            max_value_actions = [action for action, value in enumerate(values) if value == max_value]
            
            prob_for_each_max_action = 1 / len(max_value_actions)
            
            new_policy[i][j] = np.array([prob_for_each_max_action if action in max_value_actions else 0.0 
                                          for action in range(num_actions)])
    
    return new_policy

In [58]:
value_function # k=8

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.10198669, 0.25961761, 0.43720398, 0.        ],
       [0.        , 0.19021759, 0.61060791, 1.16137543, 0.        ],
       [0.        , 0.31416626, 1.13673248, 1.92980957, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [59]:
new_policy=max_policy(value_function)

In [62]:
print("k=8 갱신된 정책:")
actions = ['상', '하', '좌', '우']
for i in range(1, num_rows + 1):
    for j in range(1, num_cols + 1):
        print(f"({i},{j}): ", dict(zip(actions, new_policy[i][j])))

k=8 갱신된 정책:
(1,1):  {'상': 0.0, '하': 0.0, '좌': 0.0, '우': 1.0}
(1,2):  {'상': 0.0, '하': 1.0, '좌': 0.0, '우': 0.0}
(1,3):  {'상': 0.0, '하': 1.0, '좌': 0.0, '우': 0.0}
(2,1):  {'상': 0.0, '하': 0.0, '좌': 0.0, '우': 1.0}
(2,2):  {'상': 0.0, '하': 0.0, '좌': 0.0, '우': 1.0}
(2,3):  {'상': 0.0, '하': 1.0, '좌': 0.0, '우': 0.0}
(3,1):  {'상': 0.0, '하': 0.0, '좌': 0.0, '우': 1.0}
(3,2):  {'상': 0.0, '하': 0.0, '좌': 0.0, '우': 1.0}
(3,3):  {'상': 0.0, '하': 0.5, '좌': 0.0, '우': 0.5}
